export const MINI_BOSS_PHASE_TWO: Record<string, any>;
export const CHARGED_ATTACK: Record<string, number>;
export const PARRY_CHAIN: Record<string, number>;
export function getMiniBossPhaseTwo(bossId: string): any;
export function shouldTransitionMiniBossPhase(enemy: any): boolean;
export function buildMiniBossPhaseTransition(enemy: any, phaseTwo?: any): any;
export function applyMiniBossPhaseTransition(enemy: any, phaseTwo?: any): any;
export function tickMiniBossInvulnerability(enemy: any, dt: number): number;
export function resolveParryChain(player: any): any;
export function tickParryChain(player: any, dt: number): number;
export function resetParryChain(player: any): void;
export function canStartChargedAttack(player: any, mode?: string): boolean;
export function startChargedAttack(player: any, traits?: string[], mode?: string): boolean;
export function tickChargedAttack(player: any, dt: number): boolean;
export function clearChargedAttack(player: any): void;
export function cancelChargedAttack(player: any): boolean;
