export declare const BASE_COMBOS: Array<{ duration: number; cooldown: number; reach: number; arc: number; damage: number; stamina: number; lunge: number; knock: number }>;
export declare const DODGE_STAMINA_COST: number;
export declare const DODGE_COOLDOWN: number;
export function resolveNextComboStep(currentStep: number, comboWindow: number): number;
export function getComboForStep(step: number): any;
export function canAttack(player: any, minStamina?: number): boolean;
export function canDodge(player: any): boolean;
export function resolveStaminaRegenRate(player: any, progressionMods?: any): number;
export function isInSwingArc(px: number, py: number, angle: number, tx: number, ty: number, reach: number, arc: number): boolean;
export function resolveEnemyStagger(baseDamage: number, swing: any, enemy: any): { knockback: number; stagger: number };
