// Locale strings for all supported languages. Extracted from main.js.
// Consumers: import LANGUAGE_PACKS and LANGUAGE_OPTIONS; look up by lang code.

export const LANGUAGE_OPTIONS = {
  en: "English",
  es: "Español",
  pt: "Português",
  fr: "Français",
  de: "Deutsch",
  it: "Italiano",
  ja: "日本語",
  tr: "Türkçe",
};

export const LANGUAGE_PACKS = {
  en: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "A dusty western sandbox RPG. Revolver vibes, sword fights, and lawless pig stampedes.",
      controls: [
        "🎮 Move: WASD or Arrow keys",
        "👀 Look: Mouse (click to lock pointer) or Arrow Left/Right",
        "⚔️ Attack: Left Mouse or Space (3-hit combo!)",
        "🛡️ Block: Right Mouse or C",
        "💬 Interact / Shop: E (talk to NPCs, browse shops)",
        "🧪 Use potion: Q",
        "🗺️ Toggle map: M, Character sheet: I, 🔇 Sound: N, 📺 Fullscreen: F",
        "💾 Quick save: K, Quick load: L",
      ],
      start: "⚔️ Enter The Wilds",
      continue: "📜 Continue Journey",
      goal: "🎯 Goal: Become the weirdest hero in Dustward: finish quests, survive slime duels, and outrun outlaw pigs.",
    },
    labels: {
      language: "Language", hp: "HP", stamina: "Stamina", xp: "XP", lvl: "Lvl",
      gold: "Gold", potions: "Potions", crystals: "Crystals", wood: "Wood", stone: "Stone",
      cores: "Cores", locked: "Locked", done: "Done", turnIn: "(Turn in)",
      location: "Location", house: "House", weather: "Weather", playerHouse: "Player House",
      valley: "Valley", owned: "Owned", sheltered: "Sheltered",
      explore: "Explore the valley and shape your path.",
      defeatedTitle: "You Were Defeated",
      recover: "Press R to recover at camp.",
      deathsLine: "Deaths: {deaths}. The slimes send their regards.",
      shopTitle: "🏪 Trader Nyx's Emporium",
      shopHeader: "Your Gold: {gold}   [↑/↓ to browse, Enter/E to buy, Esc to close]",
      controlsHint: "Swing: LMB/Space  Block: RMB/C  Use: E  Potion: Q  Save/Load: K/L  Map: M  Sheet: I  Sound: N",
      clear: "Clear", mist: "Mist", rain: "Rain", storm: "Storm",
    },
    quests: {
      crystal: "1) Valley Survey",
      slime: "2) Marsh Cleansing",
      wood: "3) Raise Your House",
    },
    shop: {
      healthPotionName: "Health Potion", healthPotionDesc: "Restores 38 HP. Tastes like feet.",
      megaPotionName: "Mega Potion", megaPotionDesc: "Restores 80 HP. Tastes like expensive feet.",
      crystalShardName: "Crystal Shard", crystalShardDesc: "Shiny rock. The Elder loves these.",
      mysteryBoxName: "Mystery Box", mysteryBoxDesc: "Could be anything! (It's usually rocks.)",
      sellCoresName: "Sell Slime Cores", sellCoresDesc: "Sell 1 core for 15 gold. Gross but profitable.",
      refineWeaponName: "Refine Weapon (Common→Refined)", refineWeaponDesc: "60g + 4 Ashglass. +8% damage.",
      relicWeaponName: "Relic Weapon (Refined→Relic)", relicWeaponDesc: "180g + 4 Cipher Lens. +16% damage total.",
      armorStaminaName: "Armor: Stamina Regen", armorStaminaDesc: "40g + 2 Heat Resin. +25% stamina recovery.",
      armorBlockName: "Armor: Block Efficiency", armorBlockDesc: "50g + 2 Scrap Coil. Better block window.",
      armorWeatherName: "Armor: Weather Resistance", armorWeatherDesc: "45g + 2 Pressurized Ink. Reduced weather penalty.",
      affixPrefixName: "Inscribe Prefix", affixPrefixDesc: "80g + 2 Cipher Lens. Random prefix affix on your weapon.",
      affixSuffixName: "Inscribe Suffix", affixSuffixDesc: "80g + 2 Cipher Lens. Random suffix affix on your weapon.",
    },
    season: { spring: "Primavera", summer: "Verano", fall: "Otoño", winter: "Invierno", dayLabel: "Día" },
    combat: {
      hit: "HIT", crit: "CRITICAL HIT", block: "BLOCK",
      perfect_parry: "PERFECT PARRY", perfect_dodge: "PERFECT DODGE",
      guard_break: "GUARD BREAK", low_hp: "LOW HEALTH",
      enemy_death: "ENEMY DOWN", regen: "HP RESTORED",
    },
    season: { spring: "Spring", summer: "Summer", fall: "Fall", winter: "Winter", dayLabel: "Day" },
  },
  es: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "Un RPG sandbox 3D cómicamente realista. Espadas, slimes y decisiones dudosas.",
      controls: [
        "🎮 Moverse: WASD o flechas",
        "👀 Mirar: Mouse (clic para bloquear puntero) o Flecha Izq/Der",
        "⚔️ Ataque: Clic izquierdo o Espacio (combo de 3 golpes)",
        "🛡️ Bloquear: Clic derecho o C",
        "💬 Interactuar / Tienda: E (habla con NPCs, compra)",
        "🧪 Usar poción: Q",
        "🗺️ Mapa: M, Ficha: I, 🔇 Sonido: N, 📺 Pantalla completa: F",
        "💾 Guardado rápido: K, Carga rápida: L",
      ],
      start: "⚔️ Entrar a las Tierras",
      continue: "📜 Continuar aventura",
      goal: "🎯 Meta: Completa misiones, compra equipo, construye tu casa, acaricia al gato y sobrevive al valle.",
    },
    labels: {
      language: "Idioma", hp: "HP", stamina: "Energía", xp: "XP", lvl: "Nv",
      gold: "Oro", potions: "Pociones", crystals: "Cristales", wood: "Madera", stone: "Piedra",
      cores: "Núcleos", locked: "Bloqueada", done: "Hecha", turnIn: "(Entregar)",
      location: "Lugar", house: "Casa", weather: "Clima", playerHouse: "Casa del jugador",
      valley: "Valle", owned: "Propia", sheltered: "Resguardado",
      explore: "Explora el valle y forja tu camino.",
      defeatedTitle: "Has sido derrotado", recover: "Presiona R para volver al campamento.",
      deathsLine: "Muertes: {deaths}. Los slimes te mandan saludos.",
      shopTitle: "🏪 Emporio de Nyx",
      shopHeader: "Tu oro: {gold}   [↑/↓ navegar, Enter/E comprar, Esc cerrar]",
      controlsHint: "Golpe: LMB/Espacio  Bloqueo: RMB/C  Usar: E  Poción: Q  Guardar/Cargar: K/L  Mapa: M  Ficha: I  Sonido: N",
      clear: "Despejado", mist: "Niebla", rain: "Lluvia", storm: "Tormenta",
    },
    quests: { crystal: "1) Reconocimiento del Valle", slime: "2) Limpieza del Pantano", wood: "3) Levanta tu Casa" },
    shop: {
      healthPotionName: "Poción de salud", healthPotionDesc: "Restaura 38 HP. Sabe a pies.",
      megaPotionName: "Mega poción", megaPotionDesc: "Restaura 80 HP. Sabe a pies caros.",
      crystalShardName: "Fragmento de cristal", crystalShardDesc: "Roca brillante. A la Anciana le encanta.",
      mysteryBoxName: "Caja misteriosa", mysteryBoxDesc: "¡Puede ser cualquier cosa! (Casi siempre son rocas.)",
      sellCoresName: "Vender núcleos slime", sellCoresDesc: "Vende 1 núcleo por 15 de oro.",
    },
    combat: {
      hit: "GOLPE", crit: "GOLPE CRÍTICO", block: "BLOQUEO",
      perfect_parry: "PARADA PERFECTA", perfect_dodge: "ESQUIVA PERFECTA",
      guard_break: "GUARDIA ROTA", low_hp: "VIDA BAJA",
      enemy_death: "ENEMIGO CAÍDO", regen: "HP RESTAURADO",
    },
    season: { spring: "Primavera", summer: "Verano", fall: "Otoño", winter: "Invierno", dayLabel: "Día" },
  },
  pt: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "Um RPG sandbox 3D com realismo cômico. Espadas, slimes e escolhas duvidosas.",
      controls: [
        "🎮 Mover: WASD ou setas", "👀 Olhar: Mouse (clique para travar ponteiro) ou Seta Esq/Dir",
        "⚔️ Ataque: Botão esquerdo ou Espaço (combo de 3 golpes)", "🛡️ Defesa: Botão direito ou C",
        "💬 Interagir / Loja: E (fale com NPCs, compre)", "🧪 Usar poção: Q",
        "🗺️ Mapa: M, Ficha: I, 🔇 Som: N, 📺 Tela cheia: F", "💾 Salvar rápido: K, Carregar rápido: L",
      ],
      start: "⚔️ Entrar nas Terras", continue: "📜 Continuar jornada",
      goal: "🎯 Objetivo: complete missões, compre equipamentos, construa sua casa, faça carinho no gato e sobreviva no vale.",
    },
    labels: {
      language: "Idioma", hp: "HP", stamina: "Fôlego", xp: "XP", lvl: "Nv",
      gold: "Ouro", potions: "Poções", crystals: "Cristais", wood: "Madeira", stone: "Pedra",
      cores: "Núcleos", locked: "Bloqueada", done: "Concluída", turnIn: "(Entregar)",
      location: "Local", house: "Casa", weather: "Clima", playerHouse: "Casa do jogador",
      valley: "Vale", owned: "Sua", sheltered: "Abrigado",
      explore: "Explore o vale e siga seu caminho.",
      defeatedTitle: "Você foi derrotado", recover: "Pressione R para voltar ao acampamento.",
      deathsLine: "Mortes: {deaths}. Os slimes mandam lembranças.",
      shopTitle: "🏪 Empório da Nyx",
      shopHeader: "Seu ouro: {gold}   [↑/↓ navegar, Enter/E comprar, Esc fechar]",
      controlsHint: "Golpe: LMB/Espaço  Defesa: RMB/C  Usar: E  Poção: Q  Salvar/Carregar: K/L  Mapa: M  Ficha: I  Som: N",
      clear: "Limpo", mist: "Névoa", rain: "Chuva", storm: "Tempestade",
    },
    quests: { crystal: "1) Levantamento do Vale", slime: "2) Limpeza do Pântano", wood: "3) Erga sua Casa" },
    shop: {
      healthPotionName: "Poção de vida", healthPotionDesc: "Restaura 38 HP. Gosto de pé.",
      megaPotionName: "Mega poção", megaPotionDesc: "Restaura 80 HP. Gosto de pé premium.",
      crystalShardName: "Fragmento de cristal", crystalShardDesc: "Pedra brilhante. A Anciã adora.",
      mysteryBoxName: "Caixa misteriosa", mysteryBoxDesc: "Pode ser qualquer coisa! (Normalmente pedras.)",
      sellCoresName: "Vender núcleos slime", sellCoresDesc: "Venda 1 núcleo por 15 de ouro.",
    },
    combat: {
      hit: "ACERTO", crit: "ACERTO CRÍTICO", block: "BLOQUEIO",
      perfect_parry: "APARO PERFEITO", perfect_dodge: "ESQUIVA PERFEITA",
      guard_break: "GUARDA QUEBRADA", low_hp: "VIDA BAIXA",
      enemy_death: "INIMIGO ABATIDO", regen: "HP RESTAURADO",
    },
    season: { spring: "Primavera", summer: "Verão", fall: "Outono", winter: "Inverno", dayLabel: "Dia" },
  },
  fr: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "Un RPG sandbox 3D au réalisme comique. Épées, slimes et choix discutables.",
      controls: [
        "🎮 Déplacement : WASD ou flèches", "👀 Regard : Souris (clic pour verrouiller le pointeur) ou Flèche Gauche/Droite",
        "⚔️ Attaque : Clic gauche ou Espace (combo de 3 coups)", "🛡️ Parade : Clic droit ou C",
        "💬 Interaction / Boutique : E (parler aux PNJ, acheter)", "🧪 Utiliser une potion : Q",
        "🗺️ Carte : M, Fiche : I, 🔇 Son : N, 📺 Plein écran : F", "💾 Sauvegarde rapide : K, Chargement rapide : L",
      ],
      start: "⚔️ Entrer dans les Terres", continue: "📜 Reprendre l'aventure",
      goal: "🎯 Objectif : terminez des quêtes, achetez de l'équipement, construisez votre maison, caressez le chat et survivez à la vallée.",
    },
    labels: {
      language: "Langue", hp: "PV", stamina: "Endurance", xp: "XP", lvl: "Niv",
      gold: "Or", potions: "Potions", crystals: "Cristaux", wood: "Bois", stone: "Pierre",
      cores: "Noyaux", locked: "Bloquée", done: "Terminée", turnIn: "(Rendre)",
      location: "Lieu", house: "Maison", weather: "Météo", playerHouse: "Maison du joueur",
      valley: "Vallée", owned: "À vous", sheltered: "Abrité",
      explore: "Explorez la vallée et tracez votre route.",
      defeatedTitle: "Vous avez été vaincu", recover: "Appuyez sur R pour revenir au camp.",
      deathsLine: "Morts : {deaths}. Les slimes vous saluent.",
      shopTitle: "🏪 Emporium de Nyx",
      shopHeader: "Votre or : {gold}   [↑/↓ naviguer, Entrée/E acheter, Échap fermer]",
      controlsHint: "Frappe : LMB/Espace  Parade : RMB/C  Utiliser : E  Potion : Q  Sauver/Charger : K/L  Carte : M  Fiche : I  Son : N",
      clear: "Clair", mist: "Brume", rain: "Pluie", storm: "Tempête",
    },
    quests: { crystal: "1) Repérage de la Vallée", slime: "2) Nettoyage du Marais", wood: "3) Construisez votre Maison" },
    shop: {
      healthPotionName: "Potion de soin", healthPotionDesc: "Rend 38 PV. Goût de chaussette.",
      megaPotionName: "Méga potion", megaPotionDesc: "Rend 80 PV. Goût de chaussette premium.",
      crystalShardName: "Éclat de cristal", crystalShardDesc: "Pierre brillante. L'Ancienne adore.",
      mysteryBoxName: "Boîte mystère", mysteryBoxDesc: "Ça peut être n'importe quoi ! (Souvent des pierres.)",
      sellCoresName: "Vendre des noyaux de slime", sellCoresDesc: "Vendez 1 noyau pour 15 or.",
    },
    combat: {
      hit: "TOUCHÉ", crit: "COUP CRITIQUE", block: "PARADE",
      perfect_parry: "PARADE PARFAITE", perfect_dodge: "ESQUIVE PARFAITE",
      guard_break: "GARDE BRISÉE", low_hp: "VIE BASSE",
      enemy_death: "ENNEMI ABATTU", regen: "PV RESTAURÉS",
    },
    season: { spring: "Printemps", summer: "Été", fall: "Automne", winter: "Hiver", dayLabel: "Jour" },
  },
  de: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "Ein komisch-realistisches 3D-Sandbox-RPG. Schwerter, Slimes und fragwürdige Entscheidungen.",
      controls: [
        "🎮 Bewegen: WASD oder Pfeiltasten", "👀 Blick: Maus (Klick für Pointer-Lock) oder Pfeil Links/Rechts",
        "⚔️ Angriff: Linksklick oder Leertaste (3er-Kombo)", "🛡️ Blocken: Rechtsklick oder C",
        "💬 Interagieren / Shop: E (mit NPCs reden, kaufen)", "🧪 Trank benutzen: Q",
        "🗺️ Karte: M, Bogen: I, 🔇 Sound: N, 📺 Vollbild: F", "💾 Schnell speichern: K, Schnell laden: L",
      ],
      start: "⚔️ In die Wildnis", continue: "📜 Reise fortsetzen",
      goal: "🎯 Ziel: Quests abschließen, Ausrüstung kaufen, dein Haus bauen, die Katze streicheln und im Tal überleben.",
    },
    labels: {
      language: "Sprache", hp: "LP", stamina: "Ausdauer", xp: "XP", lvl: "Lvl",
      gold: "Gold", potions: "Tränke", crystals: "Kristalle", wood: "Holz", stone: "Stein",
      cores: "Kerne", locked: "Gesperrt", done: "Erledigt", turnIn: "(Abgeben)",
      location: "Ort", house: "Haus", weather: "Wetter", playerHouse: "Spielerhaus",
      valley: "Tal", owned: "Eigen", sheltered: "Geschützt",
      explore: "Erkunde das Tal und bestimme deinen Weg.",
      defeatedTitle: "Du wurdest besiegt", recover: "Drücke R, um am Lager zu respawnen.",
      deathsLine: "Tode: {deaths}. Die Slimes grüßen freundlich.",
      shopTitle: "🏪 Nyx' Emporium",
      shopHeader: "Dein Gold: {gold}   [↑/↓ wählen, Enter/E kaufen, Esc schließen]",
      controlsHint: "Schlag: LMB/Leertaste  Block: RMB/C  Nutzen: E  Trank: Q  Speichern/Laden: K/L  Karte: M  Bogen: I  Sound: N",
      clear: "Klar", mist: "Nebel", rain: "Regen", storm: "Sturm",
    },
    quests: { crystal: "1) Talerkundung", slime: "2) Sumpfreinigung", wood: "3) Baue dein Haus" },
    shop: {
      healthPotionName: "Heiltrank", healthPotionDesc: "Stellt 38 LP wieder her. Schmeckt nach Füßen.",
      megaPotionName: "Mega-Trank", megaPotionDesc: "Stellt 80 LP wieder her. Schmeckt nach teuren Füßen.",
      crystalShardName: "Kristallsplitter", crystalShardDesc: "Glänzender Stein. Die Älteste liebt die Dinger.",
      mysteryBoxName: "Mysteriöse Kiste", mysteryBoxDesc: "Kann alles sein! (Meistens Steine.)",
      sellCoresName: "Slime-Kerne verkaufen", sellCoresDesc: "Verkaufe 1 Kern für 15 Gold.",
    },
    combat: {
      hit: "TREFFER", crit: "KRITISCHER TREFFER", block: "BLOCK",
      perfect_parry: "PERFEKTE PARADE", perfect_dodge: "PERFEKTES AUSWEICHEN",
      guard_break: "GUARD GEBROCHEN", low_hp: "WENIG LEBEN",
      enemy_death: "FEIND BESIEGT", regen: "LP WIEDERHERGESTELLT",
    },
    season: { spring: "Frühling", summer: "Sommer", fall: "Herbst", winter: "Winter", dayLabel: "Tag" },
  },
  it: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "Un RPG sandbox 3D dal realismo comico. Spade, slime e scelte discutibili.",
      controls: [
        "🎮 Muovi: WASD o frecce", "👀 Visuale: Mouse (clic per bloccare il puntatore) o Freccia Sinistra/Destra",
        "⚔️ Attacco: Clic sinistro o Spazio (combo da 3 colpi)", "🛡️ Parata: Clic destro o C",
        "💬 Interagisci / Negozio: E (parla con gli NPC, compra)", "🧪 Usa pozione: Q",
        "🗺️ Mappa: M, Scheda: I, 🔇 Audio: N, 📺 Schermo intero: F", "💾 Salvataggio rapido: K, Caricamento rapido: L",
      ],
      start: "⚔️ Entra nelle Terre", continue: "📜 Continua il viaggio",
      goal: "🎯 Obiettivo: completa missioni, compra equipaggiamento, costruisci la tua casa, accarezza il gatto e sopravvivi nella valle.",
    },
    labels: {
      language: "Lingua", hp: "PS", stamina: "Stamina", xp: "XP", lvl: "Liv",
      gold: "Oro", potions: "Pozioni", crystals: "Cristalli", wood: "Legno", stone: "Pietra",
      cores: "Nuclei", locked: "Bloccata", done: "Completata", turnIn: "(Consegna)",
      location: "Luogo", house: "Casa", weather: "Meteo", playerHouse: "Casa del giocatore",
      valley: "Valle", owned: "Di proprietà", sheltered: "Al riparo",
      explore: "Esplora la valle e scegli il tuo percorso.",
      defeatedTitle: "Sei stato sconfitto", recover: "Premi R per recuperare al campo.",
      deathsLine: "Morti: {deaths}. Gli slime ti salutano.",
      shopTitle: "🏪 Emporio di Nyx",
      shopHeader: "Il tuo oro: {gold}   [↑/↓ naviga, Invio/E compra, Esc chiudi]",
      controlsHint: "Colpo: LMB/Spazio  Parata: RMB/C  Usa: E  Pozione: Q  Salva/Carica: K/L  Mappa: M  Scheda: I  Audio: N",
      clear: "Sereno", mist: "Nebbia", rain: "Pioggia", storm: "Tempesta",
    },
    quests: { crystal: "1) Ricognizione della Valle", slime: "2) Bonifica della Palude", wood: "3) Costruisci la tua Casa" },
    shop: {
      healthPotionName: "Pozione curativa", healthPotionDesc: "Ripristina 38 PS. Sa di piedi.",
      megaPotionName: "Mega pozione", megaPotionDesc: "Ripristina 80 PS. Sa di piedi costosi.",
      crystalShardName: "Scheggia di cristallo", crystalShardDesc: "Roccia brillante. All'Anziana piace molto.",
      mysteryBoxName: "Scatola misteriosa", mysteryBoxDesc: "Può essere qualsiasi cosa! (Di solito pietre.)",
      sellCoresName: "Vendi nuclei slime", sellCoresDesc: "Vendi 1 nucleo per 15 oro.",
    },
    combat: {
      hit: "COLPO", crit: "COLPO CRITICO", block: "PARATA",
      perfect_parry: "PARATA PERFETTA", perfect_dodge: "SCHIVATA PERFETTA",
      guard_break: "GUARDIA ROTTA", low_hp: "VITA BASSA",
      enemy_death: "NEMICO ABBATTUTO", regen: "PS RIPRISTINATI",
    },
    season: { spring: "Primavera", summer: "Estate", fall: "Autunno", winter: "Inverno", dayLabel: "Giorno" },
  },
  ja: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "コミカルでリアル寄りな3DサンドボックスRPG。剣、スライム、そして微妙な人生選択。",
      controls: [
        "🎮 移動: WASD または 矢印キー", "👀 視点: マウス（クリックでポインタ固定）または 左右矢印",
        "⚔️ 攻撃: 左クリック または Space（3連コンボ）", "🛡️ ガード: 右クリック または C",
        "💬 会話 / ショップ: E（NPCと会話、買い物）", "🧪 ポーション使用: Q",
        "🗺️ マップ: M、シート: I、🔇 音: N、📺 全画面: F", "💾 クイックセーブ: K、クイックロード: L",
      ],
      start: "⚔️ 荒野へ出発", continue: "📜 冒険を再開",
      goal: "🎯 目標: クエスト達成、装備購入、家づくり、猫をなでて、皮肉なNPCと怒れるゼリーだらけの谷を生き延びよう。",
    },
    labels: {
      language: "言語", hp: "HP", stamina: "スタミナ", xp: "XP", lvl: "Lv",
      gold: "ゴールド", potions: "ポーション", crystals: "クリスタル", wood: "木材", stone: "石材",
      cores: "コア", locked: "未解放", done: "完了", turnIn: "（報告）",
      location: "場所", house: "家", weather: "天気", playerHouse: "プレイヤーの家",
      valley: "谷", owned: "所有", sheltered: "屋内",
      explore: "谷を探索し、自分の道を切り開こう。",
      defeatedTitle: "あなたは倒された", recover: "Rでキャンプに戻る。",
      deathsLine: "死亡回数: {deaths}。スライムたちが手を振っている。",
      shopTitle: "🏪 ニクス商会",
      shopHeader: "所持金: {gold}   [↑/↓ 選択, Enter/E 購入, Esc 閉じる]",
      controlsHint: "攻撃: LMB/Space  ガード: RMB/C  使用: E  ポーション: Q  セーブ/ロード: K/L  マップ: M  シート: I  音: N",
      clear: "晴れ", mist: "霧", rain: "雨", storm: "嵐",
    },
    quests: { crystal: "1) 谷の調査", slime: "2) 沼地の浄化", wood: "3) 自分の家を建てる" },
    shop: {
      healthPotionName: "回復ポーション", healthPotionDesc: "HPを38回復。味は足っぽい。",
      megaPotionName: "メガポーション", megaPotionDesc: "HPを80回復。高級な足の味。",
      crystalShardName: "クリスタルの欠片", crystalShardDesc: "キラキラした石。長老が大好き。",
      mysteryBoxName: "ミステリーボックス", mysteryBoxDesc: "何が出るかな！（だいたい石）",
      sellCoresName: "スライムコアを売る", sellCoresDesc: "コア1個を15ゴールドで売却。",
    },
    combat: {
      hit: "ヒット", crit: "クリティカル", block: "ブロック",
      perfect_parry: "完璧なパリィ", perfect_dodge: "完璧な回避",
      guard_break: "ガード崩壊", low_hp: "HP低下",
      enemy_death: "敵を撃破", regen: "HP回復",
    },
    season: { spring: "春", summer: "夏", fall: "秋", winter: "冬", dayLabel: "日" },
  },
  tr: {
    menu: {
      title: "🏜️ WESTWARD",
      subtitle: "Komik gerçekçiliğe sahip bir 3D sandbox RPG. Kılıçlar, slime'lar ve şüpheli hayat kararları.",
      controls: [
        "🎮 Hareket: WASD veya ok tuşları", "👀 Bakış: Fare (işaretçiyi kilitlemek için tıkla) veya Sol/Sağ ok",
        "⚔️ Saldırı: Sol tık veya Boşluk (3 vuruşluk kombo)", "🛡️ Blok: Sağ tık veya C",
        "💬 Etkileşim / Dükkan: E (NPC'lerle konuş, alışveriş yap)", "🧪 İksir kullan: Q",
        "🗺️ Harita: M, Sayfa: I, 🔇 Ses: N, 📺 Tam ekran: F", "💾 Hızlı kayıt: K, Hızlı yükleme: L",
      ],
      start: "⚔️ Vahşi Topraklara Gir", continue: "📜 Yolculuğa devam et",
      goal: "🎯 Hedef: görevleri tamamla, ekipman al, evini inşa et, kediyi sev ve alaycı NPC'ler ile öfkeli jellerle dolu vadide hayatta kal.",
    },
    labels: {
      language: "Dil", hp: "CP", stamina: "Dayanıklılık", xp: "XP", lvl: "Sv",
      gold: "Altın", potions: "İksirler", crystals: "Kristaller", wood: "Odun", stone: "Taş",
      cores: "Çekirdek", locked: "Kilitli", done: "Tamam", turnIn: "(Teslim et)",
      location: "Konum", house: "Ev", weather: "Hava", playerHouse: "Oyuncu Evi",
      valley: "Vadi", owned: "Sahip", sheltered: "Korunaklı",
      explore: "Vadiyi keşfet ve kendi yolunu çiz.",
      defeatedTitle: "Yenildin", recover: "Kampa dönmek için R'ye bas.",
      deathsLine: "Ölümler: {deaths}. Slime'lar selam söylüyor.",
      shopTitle: "🏪 Nyx'in Dükkanı",
      shopHeader: "Altının: {gold}   [↑/↓ gezin, Enter/E satın al, Esc kapat]",
      controlsHint: "Vuruş: LMB/Boşluk  Blok: RMB/C  Kullan: E  İksir: Q  Kaydet/Yükle: K/L  Harita: M  Sayfa: I  Ses: N",
      clear: "Açık", mist: "Sis", rain: "Yağmur", storm: "Fırtına",
    },
    quests: { crystal: "1) Vadi Keşfi", slime: "2) Bataklık Temizliği", wood: "3) Evini Kur" },
    shop: {
      healthPotionName: "Can iksiri", healthPotionDesc: "38 CP yeniler. Tadı ayak gibi.",
      megaPotionName: "Mega iksir", megaPotionDesc: "80 CP yeniler. Tadı pahalı ayak gibi.",
      crystalShardName: "Kristal parçası", crystalShardDesc: "Parlak taş. Yaşlı bunun hastası.",
      mysteryBoxName: "Gizem kutusu", mysteryBoxDesc: "Her şey çıkabilir! (Genelde taş çıkar.)",
      sellCoresName: "Slime çekirdeği sat", sellCoresDesc: "1 çekirdeği 15 altına sat.",
    },
    combat: {
      hit: "VURUŞ", crit: "KRİTİK VURUŞ", block: "BLOK",
      perfect_parry: "MÜKEMMEL PARILAMA", perfect_dodge: "MÜKEMMEL KAÇIŞ",
      guard_break: "SAVUNMA KIRILDI", low_hp: "DÜŞÜK CAN",
      enemy_death: "DÜŞMAN YIKILDI", regen: "CP YENİLENDİ",
    },
    season: { spring: "İlkbahar", summer: "Yaz", fall: "Sonbahar", winter: "Kış", dayLabel: "Gün" },
  },
};
